# mysql2 version 3.x
#   gem install mysql2
#
#   Ensure the mysql2 3 gem is defined in your Gemfile
#   gem 'mysql2'
#
# mysql2 version 3.x
#   gem install mysql2
#
#   Ensure the mysql2 3 gem is defined in your Gemfile
#   gem 'mysql2'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stats_development
  pool: 5
  username: root
  password: root

# 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stats_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stats_production
  pool: 5
  username: root
  password: root